// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TareaSemana4._2_MiguelOsorio_21551109.Controllers;

namespace TareaSemana4._2_MiguelOsorio_21551109.Migrations
{
    [DbContext(typeof(DMVDataContext))]
    [Migration("20200822175255_CrearDBTarea4.2")]
    partial class CrearDBTarea42
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGrado")
                        .HasColumnType("int");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAlumno");

                    b.HasIndex("IdGrado");

                    b.ToTable("Alumno","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Cancion", b =>
                {
                    b.Property<int>("IdCancion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("NombreCancion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCancion");

                    b.HasIndex("IdGenero");

                    b.ToTable("Cancion","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionCategoria")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categoria","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCiudad");

                    b.ToTable("Ciudad","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCourse")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCourse");

                    b.ToTable("Course","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxEmpleadosEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresa","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreGenero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGenero");

                    b.ToTable("Genero","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreGrado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGrado");

                    b.ToTable("Grado","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Profesional", b =>
                {
                    b.Property<int>("IdProfesional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EdadProfesional")
                        .HasColumnType("int");

                    b.Property<bool>("EstadoProfesional")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("NombreProfesional")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdProfesional");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Profesional","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Residencial", b =>
                {
                    b.Property<int>("IdResidencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<string>("NombreResidencial")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdResidencial");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Residencial","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EdadStudent")
                        .HasColumnType("int");

                    b.Property<string>("EstadoStudent")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreStudent")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdStudent");

                    b.ToTable("Student","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.StudentCourse", b =>
                {
                    b.Property<int>("IdStudentCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.HasKey("IdStudentCourse");

                    b.HasIndex("IdCourse");

                    b.HasIndex("IdStudent");

                    b.ToTable("StudentCourse","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AñoVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("ColorVehiculo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("MarcaVehiculo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreVehiculo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Vehiculo","dbo");
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Alumno", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Grado", "Grado")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Cancion", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Genero", "Genero")
                        .WithMany("Canciones")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Profesional", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Empresa", "Empresa")
                        .WithMany("Profesionales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Residencial", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Ciudad", "Ciudad")
                        .WithMany("Residenciales")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.StudentCourse", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("IdCourse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaSemana4._2_MiguelOsorio_21551109.Models.Vehiculo", b =>
                {
                    b.HasOne("TareaSemana4._2_MiguelOsorio_21551109.Models.Categoria", "Categoria")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
